global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "jpos-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'jpos-app'
    static_configs:
      - targets: ['jpos-app:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']