apiVersion: v1
kind: ConfigMap
metadata:
  name: jpos-config
  namespace: jpos-payment
data:
  application.yml: |
    spring:
      profiles:
        active: prod
    jpos:
      server:
        port: 8120
        host: 0.0.0.0
        max-sessions: 5000
    logging:
      level:
        com.company.jpos: INFO