apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpos-payment-app
  namespace: jpos-payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jpos-payment
  template:
    metadata:
      labels:
        app: jpos-payment
    spec:
      containers:
      - name: jpos-app
        image: jpos-payment:latest
        ports:
        - containerPort: 8080
        - containerPort: 8120
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_URL
          value: "jdbc:postgresql://postgres-service:5432/jpos"
        - name: DB_USERNAME
          value: "jpos"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jpos-secrets
              key: db-password
        - name: REDIS_HOST
          value: "redis-service"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jpos-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: config-volume
        configMap:
          name: jpos-config
      - name: logs-volume
        emptyDir: {}